machine:
  post:
    - pyenv global 2.7 3.4 3.5

dependencies:
  pre:
    - pip install --upgrade pip tox

test:
  override:
    - tox -e py27
    - tox -e py34
    - tox -e py35
    - tox -e cover
    - tox -e lint
    - tox -e docs
    - tox -e doctest

general:
  branches:
    ignore:
      - gh-pages
