language: python
sudo: false

install:
- pip install --upgrade git+git@github.com:dhermes/ci-diff-helper.git#egg=ci-diff-helper

script:
- python travis_app.py

cache:
  directories:
  - "${HOME}/.cache/pip"
