language: python
sudo: false

install:
- pip install --upgrade pip tox

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.5

script:
- tox -e py27
- tox -e py34
- tox -e py35
- tox -e cover
- tox -e lint
- tox -e docs
- tox -e doctest

after_success:
- ".tox/cover/bin/pip install coveralls"
- ".tox/cover/bin/coveralls"

cache:
  directories:
  - "${HOME}/.cache/pip"

deploy:
  provider: pypi
  user: bossylobster
  password:
    secure: 0ZFz5Jycfbk/67mULbWBloUiVLKLr44w7I4BnodV92VYELDNRop1ljbXiIexDlCVKYYxIPvhdDaFxW6lOLIAJe01/J8CDTSmp4xAwTmzDROCsJoy1+thrWj3kR6Bco6B/3kYanktoTEXIBdNWaMUJ0QnAtl3S1XLAfJcfAx7LPqv/P9jNEwHsclvL/uuniQYyhYGTBZsGo6JGSgYNwrBI2Fg3uklW69bZqVKozqeMrLbcr9+A7j5SJPRlUS6wB01sBuhLTYStdCzsKUmjjtBSuK3+s4unr5eIKui3G31sYHq1mFywY24MHgh0Vvz4C7VK/Qbbb5mqMLcuLl0MDB9K3Dn+wwDcmASg/mLOxTjrxXVQ0pw0lHN4jVilg2ttHF/HMWzyQq3srP+z6YIyR5Xn5qQvhB414r/ZA3QJgl6qgRewfo5vHzNCXSiC8aHGaHuXY7J2qa6gHlwjIg8akZorA+oknMGDcjJX+ScOEu7M6N/HmY1ziNicWkNQhYrCG6wk2xvnzjeVtcOUFuBhCzkoVj92WW4ySnXAaSIcqVgumSnJWg/CLsL3XWcmQRqbal/tDyq/3KUWzNWvrqwmm7e4mtSgTgQxVd3OqIJY6W2LMYKgKAHX2mw1O+KkFWzv1cJdphY8jZ4aTrmE82jVHlhRXxl8E+D8mF8JgdDpEXexrk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dhermes/ci-diff-helper
