language: python
sudo: false

install:
- pip install --upgrade git+https://github.com/dhermes/ci-diff-helper#ci-diff-helper

script:
- python simple_app.py

cache:
  directories:
  - "${HOME}/.cache/pip"
